### ISSUE TITLE
请问为什么会有这种报错

### ISSUE THREAD

**Issue by MeteorFlower** [msk86/ygo-card-print#4]
D:\YGOPro2\ygo-card-print\index.js:42
    const proCards = await getMultiData(cdb, ids);
                           ^

TypeError: getMultiData is not a function
    at run (D:\YGOPro2\ygo-card-print\index.js:42:28)
    at Object.<anonymous> (D:\YGOPro2\ygo-card-print\index.js:57:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_ma
in:77:12)
    at node:internal/main/run_main_module:17:47
谢谢了

**Comment by msk86** [comment]
请重新拉一下代码，重新运行一下吧！
有一个依赖从1.3.2升级到了1.3.6，版本号兼容但是实际上不兼容了。我把版本锁在1.3.2了，你再拉一下代码应该就ok了。
