### ISSUE TITLE
TypeError: getMultiData is not a function

### ISSUE THREAD

**Issue by xk6k** [msk86/ygo-card-print#8]

**Comment by liushengliuyun** [comment]
TypeError: getMultiData is not a function
    at run (C:\Users\40102\Downloads\ygo-card-print-main\index.js:42:28)
    at Object.<anonymous> (C:\Users\40102\Downloads\ygo-card-print-main\index.js:57:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.11.0

**Comment by liushengliuyun** [comment]
same question
